title: cagedbirdID
description: Code and guidance (written by Sicily Fiennes, with the assistance of Sam Watts) to identify traded animals in highly occluded contexts, based on images.
theme: jekyll-theme-cayman
logo_url: images/cagedbirdIDlogo_Credit_Alyssa_Rice.jpeg
