title: cagedbirdID
description: Code and guidance (written by Sicily Fiennes, with the assistance of Sam Watts) to identify traded animals in highly occluded contexts, based on images.
theme: jekyll-theme-cayman
logo: https://github.com/Sicily-F/cagedbirdID/blob/gh-pages/images/cagedbirdIDlogoCreditAlyssaRicecircle.jpeg
